# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90e06d66c921cd7d439eeab7eea98cdf6a8d721ffe2d63b2c857f71b83c4df57a1117e3eb65cb569c675f8f7c8aed65a0439cb37502d7cf25f3eadff0344223

test:
  secret_key_base: 0402d207de8ab4239517e5ebd6390fbb40acb0a8ca4a1e29863752dce79633b3faa22ad419d6773fa7babbaec7081daa771b97468ececff825b4aa36b38f99ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
